### ISSUE TITLE
No error message if unsuccessful connection to database.

### ISSUE THREAD

**Issue by sipian** [prateekkumarweb/couchdbjs#1]
If connection to database is unsuccessful , no error message is printed.
There is no way to tell whether connection was unsuccessful or not.
That should be added.

**Comment by prateekkumarweb** [comment]
The callback in the contructor of `couchdbjs` takes third argument `callback` whose first argument is `err`. 
Example to use :
```
const Couchdbjs = require('couchdbjs');
const db = new Couchdbjs(dbname, options, function (err) {
    if (err) console.log(err);
    else {
        // Do your stuff...
    }
});
```
